// Sources used for code:
// https://iupac.qmul.ac.uk/AtWt/

// Data Retrieved on 2026-01-01 21:22:06.950397
// Code was written automatically by src/elements/write_elements.py

use strum_macros;

#[derive(Debug, PartialEq, Eq, Clone, Copy, strum_macros::EnumString, strum_macros::Display, strum_macros::AsRefStr)]
pub enum Element {
    Xx,
    H,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Sc,
    Ti,
    V,
    Cr,
    Mn,
    Fe,
    Co,
    Ni,
    Cu,
    Zn,
    Ga,
    Ge,
    As,
    Se,
    Br,
    Kr,
    Rb,
    Sr,
    Y,
    Zr,
    Nb,
    Mo,
    Tc,
    Ru,
    Rh,
    Pd,
    Ag,
    Cd,
    In,
    Sn,
    Sb,
    Te,
    I,
    Xe,
    Cs,
    Ba,
    La,
    Ce,
    Pr,
    Nd,
    Pm,
    Sm,
    Eu,
    Gd,
    Tb,
    Dy,
    Ho,
    Er,
    Tm,
    Yb,
    Lu,
    Hf,
    Ta,
    W,
    Re,
    Os,
    Ir,
    Pt,
    Au,
    Hg,
    Tl,
    Pb,
    Bi,
    Po,
    At,
    Rn,
    Fr,
    Ra,
    Ac,
    Th,
    Pa,
    U,
    Np,
    Pu,
    Am,
    Cm,
    Bk,
    Cf,
    Es,
    Fm,
    Md,
    No,
    Lr,
    Rf,
    Db,
    Sg,
    Bh,
    Hs,
    Mt,
    Ds,
    Rg,
    Cn,
    Nh,
    Fl,
    Mc,
    Lv,
    Ts,
    Og,
}

impl Element {

    pub fn symbol(&self) -> &str {
        self.as_ref()
    }

    pub fn name(&self) -> &str {
        match *self {
            Element::Xx => "Unknown",
            Element::H  => "Hydrogen",
            Element::He => "Helium",
            Element::Li => "Lithium",
            Element::Be => "Beryllium",
            Element::B  => "Boron",
            Element::C  => "Carbon",
            Element::N  => "Nitrogen",
            Element::O  => "Oxygen",
            Element::F  => "Fluorine",
            Element::Ne => "Neon",
            Element::Na => "Sodium",
            Element::Mg => "Magnesium",
            Element::Al => "Aluminum",
            Element::Si => "Silicon",
            Element::P  => "Phosphorus",
            Element::S  => "Sulfur",
            Element::Cl => "Chlorine",
            Element::Ar => "Argon",
            Element::K  => "Potassium",
            Element::Ca => "Calcium",
            Element::Sc => "Scandium",
            Element::Ti => "Titanium",
            Element::V  => "Vanadium",
            Element::Cr => "Chromium",
            Element::Mn => "Manganese",
            Element::Fe => "Iron",
            Element::Co => "Cobalt",
            Element::Ni => "Nickel",
            Element::Cu => "Copper",
            Element::Zn => "Zinc",
            Element::Ga => "Gallium",
            Element::Ge => "Germanium",
            Element::As => "Arsenic",
            Element::Se => "Selenium",
            Element::Br => "Bromine",
            Element::Kr => "Krypton",
            Element::Rb => "Rubidium",
            Element::Sr => "Strontium",
            Element::Y  => "Yttrium",
            Element::Zr => "Zirconium",
            Element::Nb => "Niobium",
            Element::Mo => "Molybdenum",
            Element::Tc => "Technetium",
            Element::Ru => "Ruthenium",
            Element::Rh => "Rhodium",
            Element::Pd => "Palladium",
            Element::Ag => "Silver",
            Element::Cd => "Cadmium",
            Element::In => "Indium",
            Element::Sn => "Tin",
            Element::Sb => "Antimony",
            Element::Te => "Tellurium",
            Element::I  => "Iodine",
            Element::Xe => "Xenon",
            Element::Cs => "Cesium",
            Element::Ba => "Barium",
            Element::La => "Lanthanum",
            Element::Ce => "Cerium",
            Element::Pr => "Praseodymium",
            Element::Nd => "Neodymium",
            Element::Pm => "Promethium",
            Element::Sm => "Samarium",
            Element::Eu => "Europium",
            Element::Gd => "Gadolinium",
            Element::Tb => "Terbium",
            Element::Dy => "Dysprosium",
            Element::Ho => "Holmium",
            Element::Er => "Erbium",
            Element::Tm => "Thulium",
            Element::Yb => "Ytterbium",
            Element::Lu => "Lutetium",
            Element::Hf => "Hafnium",
            Element::Ta => "Tantalum",
            Element::W  => "Tungsten",
            Element::Re => "Rhenium",
            Element::Os => "Osmium",
            Element::Ir => "Iridium",
            Element::Pt => "Platinum",
            Element::Au => "Gold",
            Element::Hg => "Mercury",
            Element::Tl => "Thallium",
            Element::Pb => "Lead",
            Element::Bi => "Bismuth",
            Element::Po => "Polonium",
            Element::At => "Astatine",
            Element::Rn => "Radon",
            Element::Fr => "Francium",
            Element::Ra => "Radium",
            Element::Ac => "Actinium",
            Element::Th => "Thorium",
            Element::Pa => "Protactinium",
            Element::U  => "Uranium",
            Element::Np => "Neptunium",
            Element::Pu => "Plutonium",
            Element::Am => "Americium",
            Element::Cm => "Curium",
            Element::Bk => "Berkelium",
            Element::Cf => "Californium",
            Element::Es => "Einsteinium",
            Element::Fm => "Fermium",
            Element::Md => "Mendelevium",
            Element::No => "Nobelium",
            Element::Lr => "Lawrencium",
            Element::Rf => "Rutherfordium",
            Element::Db => "Dubnium",
            Element::Sg => "Seaborgium",
            Element::Bh => "Bohrium",
            Element::Hs => "Hassium",
            Element::Mt => "Meitnerium",
            Element::Ds => "Darmstadtium",
            Element::Rg => "Roentgenium",
            Element::Cn => "Copernicium",
            Element::Nh => "Nihonium",
            Element::Fl => "Flerovium",
            Element::Mc => "Moscovium",
            Element::Lv => "Livermorium",
            Element::Ts => "Tennessine",
            Element::Og => "Oganesson",
      }
    }

    pub fn number(&self) -> u8 {
        *self as u8
    }

    pub fn weight(&self) -> f32 {
        match *self {
            Element::Xx => 0.0,
            Element::H  => 1.0080,
            Element::He => 4.002602,
            Element::Li => 6.94,
            Element::Be => 9.0121831,
            Element::B  => 10.81,
            Element::C  => 12.011,
            Element::N  => 14.007,
            Element::O  => 15.999,
            Element::F  => 18.998403162,
            Element::Ne => 20.1797,
            Element::Na => 22.98976928,
            Element::Mg => 24.305,
            Element::Al => 26.9815384,
            Element::Si => 28.085,
            Element::P  => 30.973761998,
            Element::S  => 32.06,
            Element::Cl => 35.45,
            Element::Ar => 39.95,
            Element::K  => 39.0983,
            Element::Ca => 40.078,
            Element::Sc => 44.955907,
            Element::Ti => 47.867,
            Element::V  => 50.9415,
            Element::Cr => 51.9961,
            Element::Mn => 54.938043,
            Element::Fe => 55.845,
            Element::Co => 58.933194,
            Element::Ni => 58.6934,
            Element::Cu => 63.546,
            Element::Zn => 65.38,
            Element::Ga => 69.723,
            Element::Ge => 72.630,
            Element::As => 74.921595,
            Element::Se => 78.971,
            Element::Br => 79.904,
            Element::Kr => 83.798,
            Element::Rb => 85.4678,
            Element::Sr => 87.62,
            Element::Y  => 88.905838,
            Element::Zr => 91.222,
            Element::Nb => 92.90637,
            Element::Mo => 95.95,
            Element::Tc => 97.0,
            Element::Ru => 101.07,
            Element::Rh => 102.90549,
            Element::Pd => 106.42,
            Element::Ag => 107.8682,
            Element::Cd => 112.414,
            Element::In => 114.818,
            Element::Sn => 118.710,
            Element::Sb => 121.760,
            Element::Te => 127.60,
            Element::I  => 126.90447,
            Element::Xe => 131.293,
            Element::Cs => 132.90545196,
            Element::Ba => 137.327,
            Element::La => 138.90547,
            Element::Ce => 140.116,
            Element::Pr => 140.90766,
            Element::Nd => 144.242,
            Element::Pm => 145.0,
            Element::Sm => 150.36,
            Element::Eu => 151.964,
            Element::Gd => 157.249,
            Element::Tb => 158.925354,
            Element::Dy => 162.500,
            Element::Ho => 164.930329,
            Element::Er => 167.259,
            Element::Tm => 168.934219,
            Element::Yb => 173.045,
            Element::Lu => 174.96669,
            Element::Hf => 178.486,
            Element::Ta => 180.94788,
            Element::W  => 183.84,
            Element::Re => 186.207,
            Element::Os => 190.23,
            Element::Ir => 192.217,
            Element::Pt => 195.084,
            Element::Au => 196.966570,
            Element::Hg => 200.592,
            Element::Tl => 204.38,
            Element::Pb => 207.2,
            Element::Bi => 208.98040,
            Element::Po => 209.0,
            Element::At => 210.0,
            Element::Rn => 222.0,
            Element::Fr => 223.0,
            Element::Ra => 226.0,
            Element::Ac => 227.0,
            Element::Th => 232.0377,
            Element::Pa => 231.03588,
            Element::U  => 238.02891,
            Element::Np => 237.0,
            Element::Pu => 244.0,
            Element::Am => 243.0,
            Element::Cm => 247.0,
            Element::Bk => 247.0,
            Element::Cf => 251.0,
            Element::Es => 252.0,
            Element::Fm => 257.0,
            Element::Md => 258.0,
            Element::No => 259.0,
            Element::Lr => 262.0,
            Element::Rf => 267.0,
            Element::Db => 270.0,
            Element::Sg => 269.0,
            Element::Bh => 270.0,
            Element::Hs => 270.0,
            Element::Mt => 278.0,
            Element::Ds => 281.0,
            Element::Rg => 281.0,
            Element::Cn => 285.0,
            Element::Nh => 286.0,
            Element::Fl => 289.0,
            Element::Mc => 289.0,
            Element::Lv => 293.0,
            Element::Ts => 293.0,
            Element::Og => 294.0,
        }
    }
}

static ELEMENTS: [Element; 119] = [
    Element::Xx,
    Element::H,
    Element::He,
    Element::Li,
    Element::Be,
    Element::B,
    Element::C,
    Element::N,
    Element::O,
    Element::F,
    Element::Ne,
    Element::Na,
    Element::Mg,
    Element::Al,
    Element::Si,
    Element::P,
    Element::S,
    Element::Cl,
    Element::Ar,
    Element::K,
    Element::Ca,
    Element::Sc,
    Element::Ti,
    Element::V,
    Element::Cr,
    Element::Mn,
    Element::Fe,
    Element::Co,
    Element::Ni,
    Element::Cu,
    Element::Zn,
    Element::Ga,
    Element::Ge,
    Element::As,
    Element::Se,
    Element::Br,
    Element::Kr,
    Element::Rb,
    Element::Sr,
    Element::Y,
    Element::Zr,
    Element::Nb,
    Element::Mo,
    Element::Tc,
    Element::Ru,
    Element::Rh,
    Element::Pd,
    Element::Ag,
    Element::Cd,
    Element::In,
    Element::Sn,
    Element::Sb,
    Element::Te,
    Element::I,
    Element::Xe,
    Element::Cs,
    Element::Ba,
    Element::La,
    Element::Ce,
    Element::Pr,
    Element::Nd,
    Element::Pm,
    Element::Sm,
    Element::Eu,
    Element::Gd,
    Element::Tb,
    Element::Dy,
    Element::Ho,
    Element::Er,
    Element::Tm,
    Element::Yb,
    Element::Lu,
    Element::Hf,
    Element::Ta,
    Element::W,
    Element::Re,
    Element::Os,
    Element::Ir,
    Element::Pt,
    Element::Au,
    Element::Hg,
    Element::Tl,
    Element::Pb,
    Element::Bi,
    Element::Po,
    Element::At,
    Element::Rn,
    Element::Fr,
    Element::Ra,
    Element::Ac,
    Element::Th,
    Element::Pa,
    Element::U,
    Element::Np,
    Element::Pu,
    Element::Am,
    Element::Cm,
    Element::Bk,
    Element::Cf,
    Element::Es,
    Element::Fm,
    Element::Md,
    Element::No,
    Element::Lr,
    Element::Rf,
    Element::Db,
    Element::Sg,
    Element::Bh,
    Element::Hs,
    Element::Mt,
    Element::Ds,
    Element::Rg,
    Element::Cn,
    Element::Nh,
    Element::Fl,
    Element::Mc,
    Element::Lv,
    Element::Ts,
    Element::Og,
];

impl TryFrom<usize> for Element {
    type Error = ();

    fn try_from(number: usize) -> Result<Self, Self::Error> {
        if number < ELEMENTS.len() {
            return Ok(ELEMENTS[number])
        } else {
            Err(())
        }
    }
}
